services:
  # mongodb database
  mongodb:
    image: mongo:7.0 # 7.0 is currently the latest version
    restart: always
    env_file:
      - .env
    volumes:
      - db:/data/db # Data storage path
    # expose:
    #   - 27017 # Default port for MongoDB
    ports:
      - 27017:27017 # Default port for MongoDB

  # Mongo-express is better suited to view the Mongo database than Adminer, but the concept is similar
  # Don't keep this in a production environment, because it currently contains some security issues on Virtual machines!
  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    ports:
      - 8082:8081
    env_file:
      - .env
      
    
  # api:
  #   image: nathansegers/db-demo04-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   environment:
  #     ENVIRONMENT: DOCKER

volumes:
  db:
  